// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkt505yH1VWJofiNFY233Kjq7sARV5P5A',
    appId: '1:111039995579:web:5f103376106697839fd39e',
    messagingSenderId: '111039995579',
    projectId: 'loankeeper-8052c',
    authDomain: 'loankeeper-8052c.firebaseapp.com',
    storageBucket: 'loankeeper-8052c.appspot.com',
    measurementId: 'G-CYRVZLZXR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6mfMKWpNyOkiglg8CiDrXJ-YAJfNg0vc',
    appId: '1:111039995579:android:de9eaca7a6f3e3c89fd39e',
    messagingSenderId: '111039995579',
    projectId: 'loankeeper-8052c',
    storageBucket: 'loankeeper-8052c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBolkMUXmx5lHRLXpOEtUVnNONLX16NFY4',
    appId: '1:111039995579:ios:00905e733e999b739fd39e',
    messagingSenderId: '111039995579',
    projectId: 'loankeeper-8052c',
    storageBucket: 'loankeeper-8052c.appspot.com',
    iosBundleId: 'com.example.loanKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBolkMUXmx5lHRLXpOEtUVnNONLX16NFY4',
    appId: '1:111039995579:ios:f56660c51b172a359fd39e',
    messagingSenderId: '111039995579',
    projectId: 'loankeeper-8052c',
    storageBucket: 'loankeeper-8052c.appspot.com',
    iosBundleId: 'com.example.loanKeeper.RunnerTests',
  );
}
